# Generated by Django 5.2.3 on 2025-06-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Profile_Picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=150)),
                ('Summary', models.CharField(max_length=100)),
                ('Degree', models.CharField(max_length=100)),
                ('Institute_Name', models.CharField(max_length=100)),
                ('Year_of_Graduation', models.DateField()),
                ('Company_Name', models.CharField(max_length=100)),
                ('Position', models.CharField(max_length=100)),
                ('Years_of_Experience', models.PositiveIntegerField()),
                ('Skills', models.TextField(help_text='Enter skills separated by commas')),
                ('Hobbies', models.TextField(help_text='Enter hobbies separated by commas')),
                ('Achievements', models.TextField(help_text='Enter achievements separated by commas')),
            ],
        ),
    ]
